[project]
name = "tornado-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "auto-py-to-exe>=2.48.1",
    "psutil>=7.1.3",
    "pywin32>=311",
    "tinydb>=4.8.2",
    "tornado>=6.5.2",
]
